//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZonLogin.UserManagementProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.zon.pt/", ConfigurationName="UserManagementProxy.UserManagementSoap")]
    public interface UserManagementSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/GetCodeVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZonLogin.UserManagementProxy.GetCodeVersionResult GetCodeVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/GetCodeVersion", ReplyAction="*")]
        System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.GetCodeVersionResult> GetCodeVersionAsync();
        
        // CODEGEN: Parameter 'startTime' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/GetClientHistory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZonLogin.UserManagementProxy.GetClientHistoryResponse GetClientHistory(ZonLogin.UserManagementProxy.GetClientHistoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/GetClientHistory", ReplyAction="*")]
        System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.GetClientHistoryResponse> GetClientHistoryAsync(ZonLogin.UserManagementProxy.GetClientHistoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/QueryUserAuthentication", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZonLogin.UserManagementProxy.QueryUserAuthenticationResult QueryUserAuthentication(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/QueryUserAuthentication", ReplyAction="*")]
        System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.QueryUserAuthenticationResult> QueryUserAuthenticationAsync(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/KeepAlive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZonLogin.UserManagementProxy.UserManagementResult KeepAlive(string sessionID, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/KeepAlive", ReplyAction="*")]
        System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.UserManagementResult> KeepAliveAsync(string sessionID, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/OpenSession", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZonLogin.UserManagementProxy.OpenSessionResult OpenSession(string application, string user, string federatedSessionId, string password, string ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/OpenSession", ReplyAction="*")]
        System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.OpenSessionResult> OpenSessionAsync(string application, string user, string federatedSessionId, string password, string ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/ReuseSession", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZonLogin.UserManagementProxy.OpenSessionResult ReuseSession(string application, string parentSessionId, string user, string ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/ReuseSession", ReplyAction="*")]
        System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.OpenSessionResult> ReuseSessionAsync(string application, string parentSessionId, string user, string ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/GetUserData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZonLogin.UserManagementProxy.GetUserDataResult GetUserData(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/GetUserData", ReplyAction="*")]
        System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.GetUserDataResult> GetUserDataAsync(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/GetAccountData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZonLogin.UserManagementProxy.GetAccountDataResult GetAccountData(string accountNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/GetAccountData", ReplyAction="*")]
        System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.GetAccountDataResult> GetAccountDataAsync(string accountNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/GetSessionData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZonLogin.UserManagementProxy.GetSessionDataResult GetSessionData(string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/GetSessionData", ReplyAction="*")]
        System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.GetSessionDataResult> GetSessionDataAsync(string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/CloseSession", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZonLogin.UserManagementProxy.UserManagementResult CloseSession(string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/CloseSession", ReplyAction="*")]
        System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.UserManagementResult> CloseSessionAsync(string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/GetAttributeValues", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZonLogin.UserManagementProxy.GetAttributeValuesResult GetAttributeValues(string sessionId, string attributeMask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/GetAttributeValues", ReplyAction="*")]
        System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.GetAttributeValuesResult> GetAttributeValuesAsync(string sessionId, string attributeMask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/CreateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZonLogin.UserManagementProxy.UserManagementResult CreateUser(string userId, string authenticationMethod, string password, string clientAccount, string serviceAccount, ZonLogin.UserManagementProxy.AttributeValue[] attributeList, string activationToken, string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/CreateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.UserManagementResult> CreateUserAsync(string userId, string authenticationMethod, string password, string clientAccount, string serviceAccount, ZonLogin.UserManagementProxy.AttributeValue[] attributeList, string activationToken, string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/CreateUserEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZonLogin.UserManagementProxy.UserManagementResult CreateUserEx(string userId, string authenticationMethod, string password, string clientAccount, string serviceAccount, string activationToken, string application, string profile, ZonLogin.UserManagementProxy.AttributeValue[] attributeList, string[] disableFeatureList, string deleteUserId, string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/CreateUserEx", ReplyAction="*")]
        System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.UserManagementResult> CreateUserExAsync(string userId, string authenticationMethod, string password, string clientAccount, string serviceAccount, string activationToken, string application, string profile, ZonLogin.UserManagementProxy.AttributeValue[] attributeList, string[] disableFeatureList, string deleteUserId, string sessionId);
        
        // CODEGEN: Parameter 'quarentineTimeout' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/SetUserStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZonLogin.UserManagementProxy.SetUserStatusResponse SetUserStatus(ZonLogin.UserManagementProxy.SetUserStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/SetUserStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.SetUserStatusResponse> SetUserStatusAsync(ZonLogin.UserManagementProxy.SetUserStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/SetUserAccounts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZonLogin.UserManagementProxy.UserManagementResult SetUserAccounts(string userId, string forAccountNumber, bool changeClientAccount, string clientAccount, bool changeServiceAccount, string serviceAccount, string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/SetUserAccounts", ReplyAction="*")]
        System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.UserManagementResult> SetUserAccountsAsync(string userId, string forAccountNumber, bool changeClientAccount, string clientAccount, bool changeServiceAccount, string serviceAccount, string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/UpdateAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZonLogin.UserManagementProxy.UserManagementResult UpdateAccount(string forAccountNumber, ZonLogin.UserManagementProxy.AttributeValue[] changeAttributeList, string[] removeAttributeList, string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/UpdateAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.UserManagementResult> UpdateAccountAsync(string forAccountNumber, ZonLogin.UserManagementProxy.AttributeValue[] changeAttributeList, string[] removeAttributeList, string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/UpdateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZonLogin.UserManagementProxy.UserManagementResult UpdateUser(string userId, string newUserId, string password, string authenticationMethod, ZonLogin.UserManagementProxy.AttributeValue[] changeAttributeList, string[] removeAttributeList, string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/UpdateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.UserManagementResult> UpdateUserAsync(string userId, string newUserId, string password, string authenticationMethod, ZonLogin.UserManagementProxy.AttributeValue[] changeAttributeList, string[] removeAttributeList, string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/GrantApplicationProfile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZonLogin.UserManagementProxy.UserManagementResult GrantApplicationProfile(string userId, string application, string profile, string package, ZonLogin.UserManagementProxy.AttributeValue[] attributeList, string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/GrantApplicationProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.UserManagementResult> GrantApplicationProfileAsync(string userId, string application, string profile, string package, ZonLogin.UserManagementProxy.AttributeValue[] attributeList, string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/RevokeApplicationProfile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZonLogin.UserManagementProxy.UserManagementResult RevokeApplicationProfile(string userId, string forAccountNumber, string application, string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/RevokeApplicationProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.UserManagementResult> RevokeApplicationProfileAsync(string userId, string forAccountNumber, string application, string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/SetApplicationFeature", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZonLogin.UserManagementProxy.UserManagementResult SetApplicationFeature(string userId, string application, string[] enableFeatureList, string[] disableFeatureList, string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/SetApplicationFeature", ReplyAction="*")]
        System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.UserManagementResult> SetApplicationFeatureAsync(string userId, string application, string[] enableFeatureList, string[] disableFeatureList, string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/GetRules", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZonLogin.UserManagementProxy.GetRulesResult GetRules(string application, string transactionType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/GetRules", ReplyAction="*")]
        System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.GetRulesResult> GetRulesAsync(string application, string transactionType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/SetUserGroups", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZonLogin.UserManagementProxy.UserManagementResult SetUserGroups(string userid, string[] addGroupList, string[] removeGroupList, string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/SetUserGroups", ReplyAction="*")]
        System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.UserManagementResult> SetUserGroupsAsync(string userid, string[] addGroupList, string[] removeGroupList, string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/GetGroupData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZonLogin.UserManagementProxy.GetGroupDataResult GetGroupData(string groupID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/GetGroupData", ReplyAction="*")]
        System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.GetGroupDataResult> GetGroupDataAsync(string groupID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/ActivateUserByToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZonLogin.UserManagementProxy.ActivateUserByTokenResult ActivateUserByToken(string token, string password, string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/ActivateUserByToken", ReplyAction="*")]
        System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.ActivateUserByTokenResult> ActivateUserByTokenAsync(string token, string password, string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/GetReferenceData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ZonLogin.UserManagementProxy.GetReferenceDataResult GetReferenceData(string dataType, string application, string profile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zon.pt/GetReferenceData", ReplyAction="*")]
        System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.GetReferenceDataResult> GetReferenceDataAsync(string dataType, string application, string profile);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zon.pt/")]
    public partial class GetCodeVersionResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string projectNameField;
        
        private string branchField;
        
        private string revisionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ProjectName {
            get {
                return this.projectNameField;
            }
            set {
                this.projectNameField = value;
                this.RaisePropertyChanged("ProjectName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Branch {
            get {
                return this.branchField;
            }
            set {
                this.branchField = value;
                this.RaisePropertyChanged("Branch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Revision {
            get {
                return this.revisionField;
            }
            set {
                this.revisionField = value;
                this.RaisePropertyChanged("Revision");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zon.pt/")]
    public partial class Category : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private ReferenceData[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public ReferenceData[] Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zon.pt/")]
    public partial class ReferenceData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string labelField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
                this.RaisePropertyChanged("Label");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zon.pt/")]
    public partial class UserData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userIdField;
        
        private string stateField;
        
        private ApplicationInfo[] applicationInfoListField;
        
        private string clientAccountField;
        
        private string serviceAccountField;
        
        private string authenticationMethodField;
        
        private AttributeValue[] attributeListField;
        
        private string[] groupListField;
        
        private string tokenField;
        
        private System.Nullable<System.DateTime> quarentineTimeoutField;
        
        private string quarentineMotiveField;
        
        private bool existsInADField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public ApplicationInfo[] ApplicationInfoList {
            get {
                return this.applicationInfoListField;
            }
            set {
                this.applicationInfoListField = value;
                this.RaisePropertyChanged("ApplicationInfoList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ClientAccount {
            get {
                return this.clientAccountField;
            }
            set {
                this.clientAccountField = value;
                this.RaisePropertyChanged("ClientAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ServiceAccount {
            get {
                return this.serviceAccountField;
            }
            set {
                this.serviceAccountField = value;
                this.RaisePropertyChanged("ServiceAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string AuthenticationMethod {
            get {
                return this.authenticationMethodField;
            }
            set {
                this.authenticationMethodField = value;
                this.RaisePropertyChanged("AuthenticationMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public AttributeValue[] AttributeList {
            get {
                return this.attributeListField;
            }
            set {
                this.attributeListField = value;
                this.RaisePropertyChanged("AttributeList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public string[] GroupList {
            get {
                return this.groupListField;
            }
            set {
                this.groupListField = value;
                this.RaisePropertyChanged("GroupList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<System.DateTime> QuarentineTimeout {
            get {
                return this.quarentineTimeoutField;
            }
            set {
                this.quarentineTimeoutField = value;
                this.RaisePropertyChanged("QuarentineTimeout");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string QuarentineMotive {
            get {
                return this.quarentineMotiveField;
            }
            set {
                this.quarentineMotiveField = value;
                this.RaisePropertyChanged("QuarentineMotive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool ExistsInAD {
            get {
                return this.existsInADField;
            }
            set {
                this.existsInADField = value;
                this.RaisePropertyChanged("ExistsInAD");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zon.pt/")]
    public partial class ApplicationInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string applicationField;
        
        private string profileField;
        
        private string[] featureListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Application {
            get {
                return this.applicationField;
            }
            set {
                this.applicationField = value;
                this.RaisePropertyChanged("Application");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Profile {
            get {
                return this.profileField;
            }
            set {
                this.profileField = value;
                this.RaisePropertyChanged("Profile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public string[] FeatureList {
            get {
                return this.featureListField;
            }
            set {
                this.featureListField = value;
                this.RaisePropertyChanged("FeatureList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zon.pt/")]
    public partial class AttributeValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zon.pt/")]
    public partial class HistoryChanges : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string labelField;
        
        private string actionField;
        
        private string newValueField;
        
        private string oldValueField;
        
        private HistoryChanges[] subChangesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
                this.RaisePropertyChanged("Label");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("Action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NewValue {
            get {
                return this.newValueField;
            }
            set {
                this.newValueField = value;
                this.RaisePropertyChanged("NewValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OldValue {
            get {
                return this.oldValueField;
            }
            set {
                this.oldValueField = value;
                this.RaisePropertyChanged("OldValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public HistoryChanges[] SubChanges {
            get {
                return this.subChangesField;
            }
            set {
                this.subChangesField = value;
                this.RaisePropertyChanged("SubChanges");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zon.pt/")]
    public partial class HistoryTransactions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime timestampField;
        
        private string userIdField;
        
        private HistoryChanges[] changesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("Timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public HistoryChanges[] Changes {
            get {
                return this.changesField;
            }
            set {
                this.changesField = value;
                this.RaisePropertyChanged("Changes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zon.pt/")]
    public partial class ResultStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private string info1Field;
        
        private string info2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Info1 {
            get {
                return this.info1Field;
            }
            set {
                this.info1Field = value;
                this.RaisePropertyChanged("Info1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Info2 {
            get {
                return this.info2Field;
            }
            set {
                this.info2Field = value;
                this.RaisePropertyChanged("Info2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetReferenceDataResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActivateUserByTokenResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetGroupDataResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetRulesResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetAttributeValuesResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetSessionDataResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetAccountDataResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetUserDataResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OpenSessionResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(QueryUserAuthenticationResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetClientHistoryResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zon.pt/")]
    public partial class UserManagementResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultStatus resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResultStatus Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zon.pt/")]
    public partial class GetReferenceDataResult : UserManagementResult {
        
        private ReferenceData[] dataField;
        
        private Category[] categoriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public ReferenceData[] Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Category[] Categories {
            get {
                return this.categoriesField;
            }
            set {
                this.categoriesField = value;
                this.RaisePropertyChanged("Categories");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zon.pt/")]
    public partial class ActivateUserByTokenResult : UserManagementResult {
        
        private string userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zon.pt/")]
    public partial class GetGroupDataResult : UserManagementResult {
        
        private string[] userListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] UserList {
            get {
                return this.userListField;
            }
            set {
                this.userListField = value;
                this.RaisePropertyChanged("UserList");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zon.pt/")]
    public partial class GetRulesResult : UserManagementResult {
        
        private string[] ruleListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] RuleList {
            get {
                return this.ruleListField;
            }
            set {
                this.ruleListField = value;
                this.RaisePropertyChanged("RuleList");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zon.pt/")]
    public partial class GetAttributeValuesResult : UserManagementResult {
        
        private AttributeValue[] attributeListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public AttributeValue[] AttributeList {
            get {
                return this.attributeListField;
            }
            set {
                this.attributeListField = value;
                this.RaisePropertyChanged("AttributeList");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zon.pt/")]
    public partial class GetSessionDataResult : UserManagementResult {
        
        private string applicationField;
        
        private string userIdField;
        
        private string clientAccountField;
        
        private string serviceAcccountField;
        
        private string profileField;
        
        private string[] featureListField;
        
        private AttributeValue[] attributeListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Application {
            get {
                return this.applicationField;
            }
            set {
                this.applicationField = value;
                this.RaisePropertyChanged("Application");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ClientAccount {
            get {
                return this.clientAccountField;
            }
            set {
                this.clientAccountField = value;
                this.RaisePropertyChanged("ClientAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ServiceAcccount {
            get {
                return this.serviceAcccountField;
            }
            set {
                this.serviceAcccountField = value;
                this.RaisePropertyChanged("ServiceAcccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Profile {
            get {
                return this.profileField;
            }
            set {
                this.profileField = value;
                this.RaisePropertyChanged("Profile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public string[] FeatureList {
            get {
                return this.featureListField;
            }
            set {
                this.featureListField = value;
                this.RaisePropertyChanged("FeatureList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public AttributeValue[] AttributeList {
            get {
                return this.attributeListField;
            }
            set {
                this.attributeListField = value;
                this.RaisePropertyChanged("AttributeList");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zon.pt/")]
    public partial class GetAccountDataResult : UserManagementResult {
        
        private UserData[] userListField;
        
        private string[] serviceAccountListField;
        
        private string clientAccountField;
        
        private AttributeValue[] attributeListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public UserData[] UserList {
            get {
                return this.userListField;
            }
            set {
                this.userListField = value;
                this.RaisePropertyChanged("UserList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] ServiceAccountList {
            get {
                return this.serviceAccountListField;
            }
            set {
                this.serviceAccountListField = value;
                this.RaisePropertyChanged("ServiceAccountList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ClientAccount {
            get {
                return this.clientAccountField;
            }
            set {
                this.clientAccountField = value;
                this.RaisePropertyChanged("ClientAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public AttributeValue[] AttributeList {
            get {
                return this.attributeListField;
            }
            set {
                this.attributeListField = value;
                this.RaisePropertyChanged("AttributeList");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zon.pt/")]
    public partial class GetUserDataResult : UserManagementResult {
        
        private string stateField;
        
        private ApplicationInfo[] applicationInfoListField;
        
        private string clientAccountField;
        
        private string serviceAccountField;
        
        private string authenticationMethodField;
        
        private AttributeValue[] attributeListField;
        
        private string[] groupListField;
        
        private string tokenField;
        
        private System.Nullable<System.DateTime> quarentineTimeoutField;
        
        private string quarentineMotiveField;
        
        private bool existsInADField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public ApplicationInfo[] ApplicationInfoList {
            get {
                return this.applicationInfoListField;
            }
            set {
                this.applicationInfoListField = value;
                this.RaisePropertyChanged("ApplicationInfoList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ClientAccount {
            get {
                return this.clientAccountField;
            }
            set {
                this.clientAccountField = value;
                this.RaisePropertyChanged("ClientAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ServiceAccount {
            get {
                return this.serviceAccountField;
            }
            set {
                this.serviceAccountField = value;
                this.RaisePropertyChanged("ServiceAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AuthenticationMethod {
            get {
                return this.authenticationMethodField;
            }
            set {
                this.authenticationMethodField = value;
                this.RaisePropertyChanged("AuthenticationMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public AttributeValue[] AttributeList {
            get {
                return this.attributeListField;
            }
            set {
                this.attributeListField = value;
                this.RaisePropertyChanged("AttributeList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public string[] GroupList {
            get {
                return this.groupListField;
            }
            set {
                this.groupListField = value;
                this.RaisePropertyChanged("GroupList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<System.DateTime> QuarentineTimeout {
            get {
                return this.quarentineTimeoutField;
            }
            set {
                this.quarentineTimeoutField = value;
                this.RaisePropertyChanged("QuarentineTimeout");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string QuarentineMotive {
            get {
                return this.quarentineMotiveField;
            }
            set {
                this.quarentineMotiveField = value;
                this.RaisePropertyChanged("QuarentineMotive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool ExistsInAD {
            get {
                return this.existsInADField;
            }
            set {
                this.existsInADField = value;
                this.RaisePropertyChanged("ExistsInAD");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zon.pt/")]
    public partial class OpenSessionResult : UserManagementResult {
        
        private string sessionIdField;
        
        private string clientAccountField;
        
        private string serviceAccountField;
        
        private string profileField;
        
        private string[] featureListField;
        
        private AttributeValue[] attributeListField;
        
        private string locationAddressField;
        
        private string locationCountryField;
        
        private string locationCityField;
        
        private string locationZipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
                this.RaisePropertyChanged("SessionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ClientAccount {
            get {
                return this.clientAccountField;
            }
            set {
                this.clientAccountField = value;
                this.RaisePropertyChanged("ClientAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ServiceAccount {
            get {
                return this.serviceAccountField;
            }
            set {
                this.serviceAccountField = value;
                this.RaisePropertyChanged("ServiceAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Profile {
            get {
                return this.profileField;
            }
            set {
                this.profileField = value;
                this.RaisePropertyChanged("Profile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public string[] FeatureList {
            get {
                return this.featureListField;
            }
            set {
                this.featureListField = value;
                this.RaisePropertyChanged("FeatureList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public AttributeValue[] AttributeList {
            get {
                return this.attributeListField;
            }
            set {
                this.attributeListField = value;
                this.RaisePropertyChanged("AttributeList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string LocationAddress {
            get {
                return this.locationAddressField;
            }
            set {
                this.locationAddressField = value;
                this.RaisePropertyChanged("LocationAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string LocationCountry {
            get {
                return this.locationCountryField;
            }
            set {
                this.locationCountryField = value;
                this.RaisePropertyChanged("LocationCountry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string LocationCity {
            get {
                return this.locationCityField;
            }
            set {
                this.locationCityField = value;
                this.RaisePropertyChanged("LocationCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string LocationZip {
            get {
                return this.locationZipField;
            }
            set {
                this.locationZipField = value;
                this.RaisePropertyChanged("LocationZip");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zon.pt/")]
    public partial class QueryUserAuthenticationResult : UserManagementResult {
        
        private string authenticationMethodField;
        
        private string lastIPField;
        
        private System.DateTime lastLoginTimestampField;
        
        private string lastLocationCountryField;
        
        private string lastLocationCityField;
        
        private string lastLocationZipCodeField;
        
        private string lastLocationAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AuthenticationMethod {
            get {
                return this.authenticationMethodField;
            }
            set {
                this.authenticationMethodField = value;
                this.RaisePropertyChanged("AuthenticationMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LastIP {
            get {
                return this.lastIPField;
            }
            set {
                this.lastIPField = value;
                this.RaisePropertyChanged("LastIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime LastLoginTimestamp {
            get {
                return this.lastLoginTimestampField;
            }
            set {
                this.lastLoginTimestampField = value;
                this.RaisePropertyChanged("LastLoginTimestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LastLocationCountry {
            get {
                return this.lastLocationCountryField;
            }
            set {
                this.lastLocationCountryField = value;
                this.RaisePropertyChanged("LastLocationCountry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LastLocationCity {
            get {
                return this.lastLocationCityField;
            }
            set {
                this.lastLocationCityField = value;
                this.RaisePropertyChanged("LastLocationCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LastLocationZipCode {
            get {
                return this.lastLocationZipCodeField;
            }
            set {
                this.lastLocationZipCodeField = value;
                this.RaisePropertyChanged("LastLocationZipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string LastLocationAddress {
            get {
                return this.lastLocationAddressField;
            }
            set {
                this.lastLocationAddressField = value;
                this.RaisePropertyChanged("LastLocationAddress");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zon.pt/")]
    public partial class GetClientHistoryResult : UserManagementResult {
        
        private HistoryTransactions[] transactionsField;
        
        private System.DateTime lastTransactionTimeField;
        
        private bool eOFField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public HistoryTransactions[] Transactions {
            get {
                return this.transactionsField;
            }
            set {
                this.transactionsField = value;
                this.RaisePropertyChanged("Transactions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime LastTransactionTime {
            get {
                return this.lastTransactionTimeField;
            }
            set {
                this.lastTransactionTimeField = value;
                this.RaisePropertyChanged("LastTransactionTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool EOF {
            get {
                return this.eOFField;
            }
            set {
                this.eOFField = value;
                this.RaisePropertyChanged("EOF");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClientHistory", WrapperNamespace="http://www.zon.pt/", IsWrapped=true)]
    public partial class GetClientHistoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.zon.pt/", Order=0)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.zon.pt/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> startTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.zon.pt/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> endTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.zon.pt/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> maxChanges;
        
        public GetClientHistoryRequest() {
        }
        
        public GetClientHistoryRequest(string userId, System.Nullable<System.DateTime> startTime, System.Nullable<System.DateTime> endTime, System.Nullable<int> maxChanges) {
            this.userId = userId;
            this.startTime = startTime;
            this.endTime = endTime;
            this.maxChanges = maxChanges;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClientHistoryResponse", WrapperNamespace="http://www.zon.pt/", IsWrapped=true)]
    public partial class GetClientHistoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.zon.pt/", Order=0)]
        public ZonLogin.UserManagementProxy.GetClientHistoryResult GetClientHistoryResult;
        
        public GetClientHistoryResponse() {
        }
        
        public GetClientHistoryResponse(ZonLogin.UserManagementProxy.GetClientHistoryResult GetClientHistoryResult) {
            this.GetClientHistoryResult = GetClientHistoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetUserStatus", WrapperNamespace="http://www.zon.pt/", IsWrapped=true)]
    public partial class SetUserStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.zon.pt/", Order=0)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.zon.pt/", Order=1)]
        public string forAccountNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.zon.pt/", Order=2)]
        public bool setDisabled;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.zon.pt/", Order=3)]
        public bool enableUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.zon.pt/", Order=4)]
        public bool setQuarentine;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.zon.pt/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> quarentineTimeout;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.zon.pt/", Order=6)]
        public string quarentineMotive;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.zon.pt/", Order=7)]
        public string sessionId;
        
        public SetUserStatusRequest() {
        }
        
        public SetUserStatusRequest(string userId, string forAccountNumber, bool setDisabled, bool enableUser, bool setQuarentine, System.Nullable<System.DateTime> quarentineTimeout, string quarentineMotive, string sessionId) {
            this.userId = userId;
            this.forAccountNumber = forAccountNumber;
            this.setDisabled = setDisabled;
            this.enableUser = enableUser;
            this.setQuarentine = setQuarentine;
            this.quarentineTimeout = quarentineTimeout;
            this.quarentineMotive = quarentineMotive;
            this.sessionId = sessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetUserStatusResponse", WrapperNamespace="http://www.zon.pt/", IsWrapped=true)]
    public partial class SetUserStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.zon.pt/", Order=0)]
        public ZonLogin.UserManagementProxy.UserManagementResult SetUserStatusResult;
        
        public SetUserStatusResponse() {
        }
        
        public SetUserStatusResponse(ZonLogin.UserManagementProxy.UserManagementResult SetUserStatusResult) {
            this.SetUserStatusResult = SetUserStatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserManagementSoapChannel : ZonLogin.UserManagementProxy.UserManagementSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserManagementSoapClient : System.ServiceModel.ClientBase<ZonLogin.UserManagementProxy.UserManagementSoap>, ZonLogin.UserManagementProxy.UserManagementSoap {
        
        public UserManagementSoapClient() {
        }
        
        public UserManagementSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserManagementSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagementSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagementSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ZonLogin.UserManagementProxy.GetCodeVersionResult GetCodeVersion() {
            return base.Channel.GetCodeVersion();
        }
        
        public System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.GetCodeVersionResult> GetCodeVersionAsync() {
            return base.Channel.GetCodeVersionAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZonLogin.UserManagementProxy.GetClientHistoryResponse ZonLogin.UserManagementProxy.UserManagementSoap.GetClientHistory(ZonLogin.UserManagementProxy.GetClientHistoryRequest request) {
            return base.Channel.GetClientHistory(request);
        }
        
        public ZonLogin.UserManagementProxy.GetClientHistoryResult GetClientHistory(string userId, System.Nullable<System.DateTime> startTime, System.Nullable<System.DateTime> endTime, System.Nullable<int> maxChanges) {
            ZonLogin.UserManagementProxy.GetClientHistoryRequest inValue = new ZonLogin.UserManagementProxy.GetClientHistoryRequest();
            inValue.userId = userId;
            inValue.startTime = startTime;
            inValue.endTime = endTime;
            inValue.maxChanges = maxChanges;
            ZonLogin.UserManagementProxy.GetClientHistoryResponse retVal = ((ZonLogin.UserManagementProxy.UserManagementSoap)(this)).GetClientHistory(inValue);
            return retVal.GetClientHistoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.GetClientHistoryResponse> ZonLogin.UserManagementProxy.UserManagementSoap.GetClientHistoryAsync(ZonLogin.UserManagementProxy.GetClientHistoryRequest request) {
            return base.Channel.GetClientHistoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.GetClientHistoryResponse> GetClientHistoryAsync(string userId, System.Nullable<System.DateTime> startTime, System.Nullable<System.DateTime> endTime, System.Nullable<int> maxChanges) {
            ZonLogin.UserManagementProxy.GetClientHistoryRequest inValue = new ZonLogin.UserManagementProxy.GetClientHistoryRequest();
            inValue.userId = userId;
            inValue.startTime = startTime;
            inValue.endTime = endTime;
            inValue.maxChanges = maxChanges;
            return ((ZonLogin.UserManagementProxy.UserManagementSoap)(this)).GetClientHistoryAsync(inValue);
        }
        
        public ZonLogin.UserManagementProxy.QueryUserAuthenticationResult QueryUserAuthentication(string userId) {
            return base.Channel.QueryUserAuthentication(userId);
        }
        
        public System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.QueryUserAuthenticationResult> QueryUserAuthenticationAsync(string userId) {
            return base.Channel.QueryUserAuthenticationAsync(userId);
        }
        
        public ZonLogin.UserManagementProxy.UserManagementResult KeepAlive(string sessionID, string password) {
            return base.Channel.KeepAlive(sessionID, password);
        }
        
        public System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.UserManagementResult> KeepAliveAsync(string sessionID, string password) {
            return base.Channel.KeepAliveAsync(sessionID, password);
        }
        
        public ZonLogin.UserManagementProxy.OpenSessionResult OpenSession(string application, string user, string federatedSessionId, string password, string ipAddress) {
            return base.Channel.OpenSession(application, user, federatedSessionId, password, ipAddress);
        }
        
        public System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.OpenSessionResult> OpenSessionAsync(string application, string user, string federatedSessionId, string password, string ipAddress) {
            return base.Channel.OpenSessionAsync(application, user, federatedSessionId, password, ipAddress);
        }
        
        public ZonLogin.UserManagementProxy.OpenSessionResult ReuseSession(string application, string parentSessionId, string user, string ipAddress) {
            return base.Channel.ReuseSession(application, parentSessionId, user, ipAddress);
        }
        
        public System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.OpenSessionResult> ReuseSessionAsync(string application, string parentSessionId, string user, string ipAddress) {
            return base.Channel.ReuseSessionAsync(application, parentSessionId, user, ipAddress);
        }
        
        public ZonLogin.UserManagementProxy.GetUserDataResult GetUserData(string user) {
            return base.Channel.GetUserData(user);
        }
        
        public System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.GetUserDataResult> GetUserDataAsync(string user) {
            return base.Channel.GetUserDataAsync(user);
        }
        
        public ZonLogin.UserManagementProxy.GetAccountDataResult GetAccountData(string accountNumber) {
            return base.Channel.GetAccountData(accountNumber);
        }
        
        public System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.GetAccountDataResult> GetAccountDataAsync(string accountNumber) {
            return base.Channel.GetAccountDataAsync(accountNumber);
        }
        
        public ZonLogin.UserManagementProxy.GetSessionDataResult GetSessionData(string sessionId) {
            return base.Channel.GetSessionData(sessionId);
        }
        
        public System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.GetSessionDataResult> GetSessionDataAsync(string sessionId) {
            return base.Channel.GetSessionDataAsync(sessionId);
        }
        
        public ZonLogin.UserManagementProxy.UserManagementResult CloseSession(string sessionId) {
            return base.Channel.CloseSession(sessionId);
        }
        
        public System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.UserManagementResult> CloseSessionAsync(string sessionId) {
            return base.Channel.CloseSessionAsync(sessionId);
        }
        
        public ZonLogin.UserManagementProxy.GetAttributeValuesResult GetAttributeValues(string sessionId, string attributeMask) {
            return base.Channel.GetAttributeValues(sessionId, attributeMask);
        }
        
        public System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.GetAttributeValuesResult> GetAttributeValuesAsync(string sessionId, string attributeMask) {
            return base.Channel.GetAttributeValuesAsync(sessionId, attributeMask);
        }
        
        public ZonLogin.UserManagementProxy.UserManagementResult CreateUser(string userId, string authenticationMethod, string password, string clientAccount, string serviceAccount, ZonLogin.UserManagementProxy.AttributeValue[] attributeList, string activationToken, string sessionId) {
            return base.Channel.CreateUser(userId, authenticationMethod, password, clientAccount, serviceAccount, attributeList, activationToken, sessionId);
        }
        
        public System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.UserManagementResult> CreateUserAsync(string userId, string authenticationMethod, string password, string clientAccount, string serviceAccount, ZonLogin.UserManagementProxy.AttributeValue[] attributeList, string activationToken, string sessionId) {
            return base.Channel.CreateUserAsync(userId, authenticationMethod, password, clientAccount, serviceAccount, attributeList, activationToken, sessionId);
        }
        
        public ZonLogin.UserManagementProxy.UserManagementResult CreateUserEx(string userId, string authenticationMethod, string password, string clientAccount, string serviceAccount, string activationToken, string application, string profile, ZonLogin.UserManagementProxy.AttributeValue[] attributeList, string[] disableFeatureList, string deleteUserId, string sessionId) {
            return base.Channel.CreateUserEx(userId, authenticationMethod, password, clientAccount, serviceAccount, activationToken, application, profile, attributeList, disableFeatureList, deleteUserId, sessionId);
        }
        
        public System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.UserManagementResult> CreateUserExAsync(string userId, string authenticationMethod, string password, string clientAccount, string serviceAccount, string activationToken, string application, string profile, ZonLogin.UserManagementProxy.AttributeValue[] attributeList, string[] disableFeatureList, string deleteUserId, string sessionId) {
            return base.Channel.CreateUserExAsync(userId, authenticationMethod, password, clientAccount, serviceAccount, activationToken, application, profile, attributeList, disableFeatureList, deleteUserId, sessionId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZonLogin.UserManagementProxy.SetUserStatusResponse ZonLogin.UserManagementProxy.UserManagementSoap.SetUserStatus(ZonLogin.UserManagementProxy.SetUserStatusRequest request) {
            return base.Channel.SetUserStatus(request);
        }
        
        public ZonLogin.UserManagementProxy.UserManagementResult SetUserStatus(string userId, string forAccountNumber, bool setDisabled, bool enableUser, bool setQuarentine, System.Nullable<System.DateTime> quarentineTimeout, string quarentineMotive, string sessionId) {
            ZonLogin.UserManagementProxy.SetUserStatusRequest inValue = new ZonLogin.UserManagementProxy.SetUserStatusRequest();
            inValue.userId = userId;
            inValue.forAccountNumber = forAccountNumber;
            inValue.setDisabled = setDisabled;
            inValue.enableUser = enableUser;
            inValue.setQuarentine = setQuarentine;
            inValue.quarentineTimeout = quarentineTimeout;
            inValue.quarentineMotive = quarentineMotive;
            inValue.sessionId = sessionId;
            ZonLogin.UserManagementProxy.SetUserStatusResponse retVal = ((ZonLogin.UserManagementProxy.UserManagementSoap)(this)).SetUserStatus(inValue);
            return retVal.SetUserStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.SetUserStatusResponse> ZonLogin.UserManagementProxy.UserManagementSoap.SetUserStatusAsync(ZonLogin.UserManagementProxy.SetUserStatusRequest request) {
            return base.Channel.SetUserStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.SetUserStatusResponse> SetUserStatusAsync(string userId, string forAccountNumber, bool setDisabled, bool enableUser, bool setQuarentine, System.Nullable<System.DateTime> quarentineTimeout, string quarentineMotive, string sessionId) {
            ZonLogin.UserManagementProxy.SetUserStatusRequest inValue = new ZonLogin.UserManagementProxy.SetUserStatusRequest();
            inValue.userId = userId;
            inValue.forAccountNumber = forAccountNumber;
            inValue.setDisabled = setDisabled;
            inValue.enableUser = enableUser;
            inValue.setQuarentine = setQuarentine;
            inValue.quarentineTimeout = quarentineTimeout;
            inValue.quarentineMotive = quarentineMotive;
            inValue.sessionId = sessionId;
            return ((ZonLogin.UserManagementProxy.UserManagementSoap)(this)).SetUserStatusAsync(inValue);
        }
        
        public ZonLogin.UserManagementProxy.UserManagementResult SetUserAccounts(string userId, string forAccountNumber, bool changeClientAccount, string clientAccount, bool changeServiceAccount, string serviceAccount, string sessionId) {
            return base.Channel.SetUserAccounts(userId, forAccountNumber, changeClientAccount, clientAccount, changeServiceAccount, serviceAccount, sessionId);
        }
        
        public System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.UserManagementResult> SetUserAccountsAsync(string userId, string forAccountNumber, bool changeClientAccount, string clientAccount, bool changeServiceAccount, string serviceAccount, string sessionId) {
            return base.Channel.SetUserAccountsAsync(userId, forAccountNumber, changeClientAccount, clientAccount, changeServiceAccount, serviceAccount, sessionId);
        }
        
        public ZonLogin.UserManagementProxy.UserManagementResult UpdateAccount(string forAccountNumber, ZonLogin.UserManagementProxy.AttributeValue[] changeAttributeList, string[] removeAttributeList, string sessionId) {
            return base.Channel.UpdateAccount(forAccountNumber, changeAttributeList, removeAttributeList, sessionId);
        }
        
        public System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.UserManagementResult> UpdateAccountAsync(string forAccountNumber, ZonLogin.UserManagementProxy.AttributeValue[] changeAttributeList, string[] removeAttributeList, string sessionId) {
            return base.Channel.UpdateAccountAsync(forAccountNumber, changeAttributeList, removeAttributeList, sessionId);
        }
        
        public ZonLogin.UserManagementProxy.UserManagementResult UpdateUser(string userId, string newUserId, string password, string authenticationMethod, ZonLogin.UserManagementProxy.AttributeValue[] changeAttributeList, string[] removeAttributeList, string sessionId) {
            return base.Channel.UpdateUser(userId, newUserId, password, authenticationMethod, changeAttributeList, removeAttributeList, sessionId);
        }
        
        public System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.UserManagementResult> UpdateUserAsync(string userId, string newUserId, string password, string authenticationMethod, ZonLogin.UserManagementProxy.AttributeValue[] changeAttributeList, string[] removeAttributeList, string sessionId) {
            return base.Channel.UpdateUserAsync(userId, newUserId, password, authenticationMethod, changeAttributeList, removeAttributeList, sessionId);
        }
        
        public ZonLogin.UserManagementProxy.UserManagementResult GrantApplicationProfile(string userId, string application, string profile, string package, ZonLogin.UserManagementProxy.AttributeValue[] attributeList, string sessionId) {
            return base.Channel.GrantApplicationProfile(userId, application, profile, package, attributeList, sessionId);
        }
        
        public System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.UserManagementResult> GrantApplicationProfileAsync(string userId, string application, string profile, string package, ZonLogin.UserManagementProxy.AttributeValue[] attributeList, string sessionId) {
            return base.Channel.GrantApplicationProfileAsync(userId, application, profile, package, attributeList, sessionId);
        }
        
        public ZonLogin.UserManagementProxy.UserManagementResult RevokeApplicationProfile(string userId, string forAccountNumber, string application, string sessionId) {
            return base.Channel.RevokeApplicationProfile(userId, forAccountNumber, application, sessionId);
        }
        
        public System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.UserManagementResult> RevokeApplicationProfileAsync(string userId, string forAccountNumber, string application, string sessionId) {
            return base.Channel.RevokeApplicationProfileAsync(userId, forAccountNumber, application, sessionId);
        }
        
        public ZonLogin.UserManagementProxy.UserManagementResult SetApplicationFeature(string userId, string application, string[] enableFeatureList, string[] disableFeatureList, string sessionId) {
            return base.Channel.SetApplicationFeature(userId, application, enableFeatureList, disableFeatureList, sessionId);
        }
        
        public System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.UserManagementResult> SetApplicationFeatureAsync(string userId, string application, string[] enableFeatureList, string[] disableFeatureList, string sessionId) {
            return base.Channel.SetApplicationFeatureAsync(userId, application, enableFeatureList, disableFeatureList, sessionId);
        }
        
        public ZonLogin.UserManagementProxy.GetRulesResult GetRules(string application, string transactionType) {
            return base.Channel.GetRules(application, transactionType);
        }
        
        public System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.GetRulesResult> GetRulesAsync(string application, string transactionType) {
            return base.Channel.GetRulesAsync(application, transactionType);
        }
        
        public ZonLogin.UserManagementProxy.UserManagementResult SetUserGroups(string userid, string[] addGroupList, string[] removeGroupList, string sessionId) {
            return base.Channel.SetUserGroups(userid, addGroupList, removeGroupList, sessionId);
        }
        
        public System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.UserManagementResult> SetUserGroupsAsync(string userid, string[] addGroupList, string[] removeGroupList, string sessionId) {
            return base.Channel.SetUserGroupsAsync(userid, addGroupList, removeGroupList, sessionId);
        }
        
        public ZonLogin.UserManagementProxy.GetGroupDataResult GetGroupData(string groupID) {
            return base.Channel.GetGroupData(groupID);
        }
        
        public System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.GetGroupDataResult> GetGroupDataAsync(string groupID) {
            return base.Channel.GetGroupDataAsync(groupID);
        }
        
        public ZonLogin.UserManagementProxy.ActivateUserByTokenResult ActivateUserByToken(string token, string password, string sessionID) {
            return base.Channel.ActivateUserByToken(token, password, sessionID);
        }
        
        public System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.ActivateUserByTokenResult> ActivateUserByTokenAsync(string token, string password, string sessionID) {
            return base.Channel.ActivateUserByTokenAsync(token, password, sessionID);
        }
        
        public ZonLogin.UserManagementProxy.GetReferenceDataResult GetReferenceData(string dataType, string application, string profile) {
            return base.Channel.GetReferenceData(dataType, application, profile);
        }
        
        public System.Threading.Tasks.Task<ZonLogin.UserManagementProxy.GetReferenceDataResult> GetReferenceDataAsync(string dataType, string application, string profile) {
            return base.Channel.GetReferenceDataAsync(dataType, application, profile);
        }
    }
}
