//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZonLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public Clients()
        {
            this.Webpages_clients = new HashSet<Webpages_clients>();
        }
    
        public string clientId { get; set; }
        public string appName { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<Webpages_clients> Webpages_clients { get; set; }
    }
}
